# Generated by Django 3.2.10 on 2022-02-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petparadise_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('w_date', models.DateField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petparadise_Admin.customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petparadise_Admin.product')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
    ]
