# Generated by Django 3.2.10 on 2022-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petparadise_Admin', '0003_feedback_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='total_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
