# Generated by Django 3.2.10 on 2022-03-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petparadise_Admin', '0005_shelter_home_shelter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
