# Generated by Django 3.2.10 on 2022-04-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petparadise_Admin', '0006_doctor_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=400),
        ),
        migrations.CreateModel(
            name='doctor_slots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_time', models.CharField(max_length=100)),
                ('s_status', models.IntegerField(null=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petparadise_Admin.doctor')),
            ],
            options={
                'db_table': 'doctor_slots',
            },
        ),
    ]
